services:
    mongo:
        image: mongo:6
        container_name: mongo
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

    server:
        platform: linux/amd64
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: truckshop-server
        restart: always
        ports:
            - '5000:5000'
        depends_on:
            - mongo
        environment:
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/truckshop
            - JWT_SECRET=supersecurejwtkey

    client:
        platform: linux/amd64
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: truckshop-client
        restart: always
        ports:
            - '3000:80'
        depends_on:
            - server

volumes:
    mongo-data:
